### ISSUE TITLE
After removing RegisterMap() application doesn't work properly

### ISSUE THREAD

**Issue by aloscha** [StarcounterApps/Chatter#17] opened 2016-06-16 22:38 UTC
Base on rule that application must works without any maps, chatter should be fixed.

**Comment by ubbeK** [comment] 2016-06-17 09:45
Images is also failing because of this

**Comment by warpech** [comment] 2017-04-24 13:27
The problem is that Chatter internally depends on mapping defined in the `RegisterMap()`. As a litmus test, the app should work standalone with that line commented out.

I will review PR #22 and decide if that is an acceptable solution or I will make an alternative solution.

**Comment by warpech** [comment] 2017-04-24 14:45
The reason why Chatter does not work with `RegisterMap() commented out is because it uses conditional mapping of two different Views for the same data class but different context:

```cs
            UriMapping.OntologyMap("/chatter/partials/chatmessages/{?}", "simplified.ring6.chatmessage", (string objectId) => objectId, (string objectId) =>
            {
                var message = DbHelper.FromID(DbHelper.Base64DecodeObjectID(objectId)) as ChatMessage;
                return message.IsDraft ? null : objectId;
            });
            UriMapping.OntologyMap("/chatter/partials/chatmessages-draft/{?}", "simplified.ring6.chatmessage", (string objectId) => objectId, (string objectId) =>
            {
                var chatMessage = (ChatMessage)DbHelper.FromID(DbHelper.Base64DecodeObjectID(objectId));
                return chatMessage.IsDraft ? objectId : null;
            });
```

[source](https://github.com/StarcounterApps/Chatter/blob/b106e64d3714e22e9b5b59b25599ae03b402d316/Api/MainHandlers.cs#L221-L230)

I think that the above usage is fine. Meaning, it was incorrect to assume that the app must also work with `UriMapping` disabled. `UriMapping` can include important logic for the app itself. The issue can be closed as "won't fix".

@ubbeK, @miyconst, @alemoi, @un-tone - WDYT?

**Comment by alemoi** [comment] 2017-04-24 17:38
@warpech I didn't get, is Chatter working standalone with mapping commented?
I mean, its not working with other apps when mapping is disabled?

**Comment by warpech** [comment] 2017-04-24 19:49
Sorry, my last proposal was wrong.

When this issue was started (Jun 17, 2016) me and @aloscha were convinced that a correctly built app should only require UriMapping to attach siblings from other apps. So, if no other apps are running, it should work as good with UriMapping rules applied or unapplied.

I think that this still holds. I have found a simple solution for this problem. Will make a PR.

**Comment by warpech** [comment] 2017-04-26 10:05
Closing as done in PR: #31

**Closed by warpech** 2017-04-26 10:05 UTC
